# Generated by Django 3.1.8 on 2021-04-06 23:21

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookBottons',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_facebookbottons', serialize=False, to='cms.cmsplugin')),
                ('Facebook', models.CharField(default='#', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_gallery', serialize=False, to='cms.cmsplugin')),
                ('Nombre', models.CharField(default='Nombre del album', max_length=50)),
                ('Descripcion', models.TextField(default='descripción')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='InstagramBottons',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_instagrambottons', serialize=False, to='cms.cmsplugin')),
                ('Instagram', models.CharField(default='#', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='LinkedinBottons',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_linkedinbottons', serialize=False, to='cms.cmsplugin')),
                ('Linkedin', models.CharField(default='#', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_players', serialize=False, to='cms.cmsplugin')),
                ('player_name', models.CharField(default='Nombre del Jugador', max_length=50)),
                ('player_position', models.CharField(default='Posicion de juego', max_length=50)),
                ('player_image', models.ImageField(upload_to='', verbose_name='Imagen del jugador')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_prizes', serialize=False, to='cms.cmsplugin')),
                ('numero', models.IntegerField(default='Número de copas')),
                ('descripcion', models.CharField(default='Descripción del premio', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='Texto',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_texto', serialize=False, to='cms.cmsplugin')),
                ('Title', models.CharField(default='Título', max_length=50)),
                ('Body', tinymce.models.HTMLField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
        migrations.CreateModel(
            name='TwitterBottons',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='myproject_twitterbottons', serialize=False, to='cms.cmsplugin')),
                ('Twitter', models.CharField(default='#', max_length=1000)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
